### ISSUE TITLE
Sorting param not saving + selected params not saved

### ISSUE THREAD

**Issue by iokinpardo** [sintacs/sintacs-mwai-frontend-chatbot-settings#3]
First at all congratulations by this amaizing plugin idea.

I have been able to update the plugin to the latest version 1.1.0. 
However after **drag & dropping several items** in the "**Parameters to Show**" section, the **Save** process has not been correcrtly executed.  Items are still under **original positions.**

Apart of this, I have **not been able to save** correctly **selected params** to show in th front-side. After saving, no items remain selected and I can just see 1 unique field in the front side, as you can see below image.

![image](https://github.com/sintacs/sintacs-mwai-frontend-chatbot-settings/assets/6673107/f890d508-7ade-4148-948e-aa2a4f5cfd57)

**Comment by sintacs** [comment]
@iokinpardo Thank you for downloading the plugin and your feedback. Please deactivate and delete the plugin then download it again and install it. It should work as intented.

**Comment by iokinpardo** [comment]
That worked, thanks.
